import os
import json
import asyncio
import operator
import re
from typing import TypedDict, List, Dict, Any, Annotated, Sequence, Optional
from langchain_core.messages import BaseMessage, AIMessage, HumanMessage
from langgraph.graph import StateGraph, START, END
from core.loaders.agents_loader import AgentsLoader
from tools.generate_image import generate_image
from tools.generate_animation_runway import generate_animation_runway
from tools.generate_animation_veo3 import generate_animation_veo3
from tools.extract_video_frames import extract_video_frames

class ContentCreationState(TypedDict, total=False):
    # --- Project Context ---
    project_dir: str                  # e.g., "pkm/wiki/software/ayla-first-words"
    topic: str                        # e.g., "dog"

    # --- Instruction Documents ---
    manifest_path: str                # e.g., "{project_dir}/01_Project_Manifest.md"
    creator_instructions_path: str    # e.g., "{project_dir}/02_Creator_Instructions.md"
    qc_playbook_path: str             # e.g., "{project_dir}/03_QC_Playbook.md"

    # --- Asset Paths ---
    output_dir: str                   # e.g., "{project_dir}/assets/{topic}"
    image_path: str                   # e.g., "{output_dir}/{topic}_image.jpg"
    video_plot_path: str              # e.g., "{output_dir}/{topic}_video_plot.md"
    video_path: str                   # e.g., "{output_dir}/{topic}_video.mp4"
    copy_path: str                    # e.g., "{output_dir}/{topic}_copy.md"

    # --- Internal Graph State & QC ---
    image_prompt: str
    video_plot_content: str
    video_plot_qc_passed: bool
    video_plot_feedback: str

    extracted_frames: List[str]       # Generated by extract_video_frames
    qc_timestamps: List[float]        # Configurable list of timestamps, default [1.0, 2.5, 4.0]
    video_qc_passed: bool
    video_qc_feedback: str

    copy_text: str
    final_package: Dict[str, Any]

    # --- Auxiliary / Runtime State ---
    video_plot_attempts: int
    max_video_plot_reviews: int
    video_qc_attempts: int
    max_video_reviews: int
    messages: Annotated[Sequence[BaseMessage], operator.add]
    query: str
    session_id: str
    error_message: str

def _extract_motion_prompt_from_plot(plot_content: str, state: Dict[str, Any]) -> str:
    """Extracts the motion prompt blockquote under **Prompt:** or Motion Prompt header from the Video Plot Markdown."""
    topic = state.get("topic", "scene")
    if plot_content:
        lines = plot_content.split("\n")
        in_prompt = False
        prompt_lines = []
        for line in lines:
            if "Motion Prompt" in line or "**Prompt:**" in line:
                in_prompt = True
                if "**Prompt:**" in line:
                    parts = line.split("**Prompt:**", 1)
                    if len(parts) > 1 and parts[1].strip():
                        prompt_lines.append(parts[1].strip().lstrip(">").strip())
                continue
            if in_prompt:
                if line.startswith("---") or line.startswith("## ") or line.startswith("# "):
                    break
                if line.strip().startswith(">"):
                    prompt_lines.append(line.strip().lstrip(">").strip())
                elif prompt_lines and not line.strip():
                    break
                elif prompt_lines:
                    prompt_lines.append(line.strip())
        if prompt_lines:
            extracted = " ".join(prompt_lines).strip()
            if extracted:
                return extracted

    return f"Cinematic video scene for topic: {topic}. High quality, smooth camera movement, focused subject animation."

# ==========================================
# 1. Node 1: setup_and_generate_image
# ==========================================
async def setup_and_generate_image_node(state: ContentCreationState):
    """Step 1: Content Creator reads project manifest and creator instructions to generate 1-shot base image."""
    project_dir = state.get("project_dir") or "pkm/wiki/software/ayla-first-words"
    topic = state.get("topic") or state.get("word") or "scene"
    output_dir = state.get("output_dir") or f"{project_dir}/assets/{topic}"
    image_path = state.get("image_path") or f"{output_dir}/{topic}_image.jpg"
    video_plot_path = state.get("video_plot_path") or f"{output_dir}/{topic}_video_plot.md"
    video_path = state.get("video_path") or f"{output_dir}/{topic}_video.mp4"
    copy_path = state.get("copy_path") or f"{output_dir}/{topic}_copy.md"
    manifest_path = state.get("manifest_path") or f"{project_dir}/01_Project_Manifest.md"
    creator_instructions_path = state.get("creator_instructions_path") or f"{project_dir}/02_Creator_Instructions.md"
    qc_playbook_path = state.get("qc_playbook_path") or f"{project_dir}/03_QC_Playbook.md"

    os.makedirs(output_dir, exist_ok=True)

    creator = AgentsLoader().get_agent("content-creator")
    prompt = (
        f"You are the Content Creator. Read the project manifest at {manifest_path} and the creator instructions at {creator_instructions_path}.\n"
        f"Generate the 1-shot base image prompt for the topic: '{topic}'.\n"
        f"Output ONLY the final image generation prompt."
    )

    image_prompt = await creator.execute(prompt, source="subgraph")
    image_prompt = image_prompt.strip().strip('"').strip("'")

    print(f"ContentCreationGraph: Generating 1-shot base image to {image_path}...")
    try:
        result = await generate_image.ainvoke({
            "prompt": image_prompt,
            "output_path": image_path,
            "agent_id": "content-creator"
        })
        if "<payload>" in result and "</payload>" in result:
            saved = result.split("<payload>")[1].split("</payload>")[0].strip()
            if saved:
                image_path = saved
    except Exception as e:
        print(f"ContentCreationGraph: Error generating image: {e}")

    return {
        "project_dir": project_dir,
        "topic": topic,
        "manifest_path": manifest_path,
        "creator_instructions_path": creator_instructions_path,
        "qc_playbook_path": qc_playbook_path,
        "output_dir": output_dir,
        "image_path": image_path,
        "video_plot_path": video_plot_path,
        "video_path": video_path,
        "copy_path": copy_path,
        "image_prompt": image_prompt
    }

# ==========================================
# 2. Node 2: draft_video_plot
# ==========================================
async def draft_video_plot_node(state: ContentCreationState):
    """Step 2: Content Creator drafts Video Plot Markdown following creator instructions."""
    topic = state.get("topic", "scene")
    creator_instructions_path = state.get("creator_instructions_path", "")
    video_plot_path = state.get("video_plot_path", "")
    feedback = state.get("video_plot_feedback", "")

    creator = AgentsLoader().get_agent("content-creator")
    prompt = (
        f"You are the Content Creator. Read {creator_instructions_path}.\n"
        f"Draft the Video Plot Markdown for the topic '{topic}' strictly following the template and constraints defined in the instructions."
    )
    if feedback:
        prompt += f"\nPrevious Brand Editor Feedback to fix:\n{feedback}\n"

    prompt += "\nOutput the complete markdown document directly."

    video_plot_content = await creator.execute(prompt, source="subgraph")
    video_plot_content = video_plot_content.strip()

    try:
        if video_plot_path:
            os.makedirs(os.path.dirname(video_plot_path), exist_ok=True)
            with open(video_plot_path, "w", encoding="utf-8") as f:
                f.write(video_plot_content)
    except Exception as e:
        print(f"ContentCreationGraph: Error saving video plot file: {e}")

    return {
        "video_plot_content": video_plot_content,
        "video_plot_path": video_plot_path,
        "video_plot_qc_passed": False
    }

# ==========================================
# 3. Node 3: audit_video_plot
# ==========================================
async def audit_video_plot_node(state: ContentCreationState):
    """Step 3: Brand Editor audits the Video Plot against QC playbook rules."""
    topic = state.get("topic", "")
    qc_playbook_path = state.get("qc_playbook_path", "")
    plot_content = state.get("video_plot_content", "")
    video_plot_path = state.get("video_plot_path", "")
    attempts = state.get("video_plot_attempts", 0) + 1

    if not plot_content and video_plot_path and os.path.isfile(video_plot_path):
        try:
            with open(video_plot_path, "r", encoding="utf-8") as f:
                plot_content = f.read()
        except Exception:
            pass

    editor = AgentsLoader().get_agent("brand-editor")
    prompt = (
        f"You are the Brand Editor. Read the QC playbook at {qc_playbook_path}.\n"
        f"Audit the following Video Plot against the playbook's rules:\n"
        f"--- Video Plot ---\n{plot_content}\n------------------\n\n"
        f"If compliant, reply 'VERDICT: APPROVED' on the first line.\n"
        f"If not, reply 'VERDICT: REJECTED' on the first line with specific required revisions."
    )

    response = await editor.execute(prompt, source="subgraph")
    is_approved = "VERDICT: APPROVED" in response.upper() or ("APPROVED" in response.upper() and "REJECTED" not in response.upper())
    feedback = "" if is_approved else response

    return {
        "video_plot_qc_passed": is_approved,
        "video_plot_feedback": feedback,
        "video_plot_attempts": attempts
    }

def should_continue_video_plot_audit(state: ContentCreationState):
    """Router: proceeds to HITL Gate 1 if approved or max attempts reached."""
    if state.get("video_plot_qc_passed"):
        return "hitl_image_and_plot_approval"
    if state.get("video_plot_attempts", 0) >= state.get("max_video_plot_reviews", 3):
        print("ContentCreationGraph: Max video plot reviews reached. Proceeding to HITL Gate 1.")
        return "hitl_image_and_plot_approval"
    return "draft_video_plot"

# ==========================================
# 🛑 HITL GATE 1: hitl_image_and_plot_approval
# ==========================================
async def hitl_image_and_plot_approval_node(state: ContentCreationState):
    """🛑 HITL GATE 1: Presents 1-shot base image and approved video plot for user review & approval."""
    topic = state.get("topic", "")
    image_path = state.get("image_path", "")
    video_plot_path = state.get("video_plot_path", "")
    plot_content = state.get("video_plot_content", "")

    summary = (
        f"🛑 **[HITL GATE 1: Image & Video Plot Approval]**\n\n"
        f"- **Topic**: `{topic}`\n"
        f"- **Base Image**: `{image_path}`\n"
        f"- **Approved Video Plot**: `{video_plot_path}`\n\n"
        f"```markdown\n{plot_content}\n```\n\n"
        f"Base image and video plot approved. Proceeding to video generation."
    )
    return {
        "messages": [AIMessage(content=summary)]
    }

# ==========================================
# 4. Node 4: generate_visual_plate
# ==========================================
async def generate_visual_plate_node(state: ContentCreationState):
    """Step 4: Content Creator uses approved motion prompt to generate video visual plate."""
    image_path = state.get("image_path", "")
    video_path = state.get("video_path", "")
    plot_content = state.get("video_plot_content", "")

    motion_prompt = _extract_motion_prompt_from_plot(plot_content, state)
    print(f"ContentCreationGraph: Generating visual plate from {image_path} to {video_path}...")

    try:
        result = await generate_animation_runway.ainvoke({
            "prompt_text": motion_prompt,
            "image_path": image_path,
            "output_path": video_path,
            "ratio": "768:1280",  # 9:16 vertical
            "duration": 5,
            "agent_id": "content-creator"
        })
        if "<payload>" in result and "</payload>" in result:
            saved = result.split("<payload>")[1].split("</payload>")[0].strip()
            if saved:
                video_path = saved
    except Exception as e:
        print(f"ContentCreationGraph: Error generating visual plate: {e}")

    return {
        "video_path": video_path
    }

# ==========================================
# 5. Node 5: extract_and_qc_frames
# ==========================================
async def extract_and_qc_frames_node(state: ContentCreationState):
    """Step 5: Brand Editor extracts video frames and performs QC based on QC playbook."""
    topic = state.get("topic", "")
    output_dir = state.get("output_dir", "")
    video_path = state.get("video_path", "")
    qc_playbook_path = state.get("qc_playbook_path", "")
    qc_timestamps = state.get("qc_timestamps") or [1.0, 2.5, 4.0]
    frames_dir = os.path.join(output_dir, "frames")
    attempts = state.get("video_qc_attempts", 0) + 1

    os.makedirs(frames_dir, exist_ok=True)
    extracted_frames = []

    try:
        res = await extract_video_frames.ainvoke({
            "video_path": video_path,
            "timestamps": qc_timestamps,
            "output_dir": frames_dir,
            "agent_id": "brand-editor"
        })
        if "<payload>" in res and "</payload>" in res:
            payload = res.split("<payload>")[1].split("</payload>")[0].strip()
            extracted_frames = [p.strip() for p in payload.split("\n") if p.strip()]
    except Exception as e:
        print(f"ContentCreationGraph: Error extracting video frames: {e}")

    if not extracted_frames and os.path.exists(frames_dir):
        extracted_frames = [
            os.path.join(frames_dir, f)
            for f in sorted(os.listdir(frames_dir))
            if f.endswith((".jpg", ".png", ".jpeg"))
        ]

    editor = AgentsLoader().get_agent("brand-editor")
    frames_list_str = "\n".join([f"- Frame {i+1} ({qc_timestamps[i] if i < len(qc_timestamps) else ''}s): {f}" for i, f in enumerate(extracted_frames)])

    prompt = (
        f"You are the Brand Editor. Read {qc_playbook_path}.\n"
        f"Audit the extracted keyframes for the topic '{topic}'.\n"
        f"Video Path: {video_path}\n"
        f"Extracted Frames:\n{frames_list_str}\n\n"
        f"Reply VERDICT: APPROVED or VERDICT: REJECTED based strictly on the playbook criteria."
    )

    response = await editor.execute(prompt, source="subgraph")
    is_approved = "VERDICT: APPROVED" in response.upper() or ("APPROVED" in response.upper() and "REJECTED" not in response.upper())
    feedback = "" if is_approved else response

    return {
        "extracted_frames": extracted_frames,
        "video_qc_passed": is_approved,
        "video_qc_feedback": feedback,
        "video_qc_attempts": attempts
    }

def should_continue_video_qc(state: ContentCreationState):
    """Router: proceeds to copywriting if video QC passed or max attempts reached."""
    if state.get("video_qc_passed"):
        return "draft_and_save_copy"
    if state.get("video_qc_attempts", 0) >= state.get("max_video_reviews", 3):
        print("ContentCreationGraph: Max video QC reviews reached. Proceeding to copywriting.")
        return "draft_and_save_copy"
    return "generate_visual_plate"

# ==========================================
# 6. Node 6: draft_and_save_copy
# ==========================================
async def draft_and_save_copy_node(state: ContentCreationState):
    """Step 6: Content Creator drafts copy, Brand Editor polishes, and saves to copy_path."""
    topic = state.get("topic", "")
    creator_instructions_path = state.get("creator_instructions_path", "")
    qc_playbook_path = state.get("qc_playbook_path", "")
    copy_path = state.get("copy_path", "")
    video_path = state.get("video_path", "")
    image_path = state.get("image_path", "")
    video_plot_path = state.get("video_plot_path", "")
    extracted_frames = state.get("extracted_frames", [])

    creator = AgentsLoader().get_agent("content-creator")
    editor = AgentsLoader().get_agent("brand-editor")

    creator_prompt = (
        f"You are the Content Creator. Read {creator_instructions_path}.\n"
        f"Draft the publication copy / captions for the topic '{topic}'."
    )
    draft_copy = await creator.execute(creator_prompt, source="subgraph")

    editor_prompt = (
        f"You are the Brand Editor. Read {qc_playbook_path}.\n"
        f"Polish the following copy for formatting, engagement, and alignment with the playbook:\n"
        f"--- Draft Copy ---\n{draft_copy}\n------------------\n"
        f"Output the final polished copy directly."
    )
    polished_copy = await editor.execute(editor_prompt, source="subgraph")
    polished_copy = polished_copy.strip()

    try:
        if copy_path:
            os.makedirs(os.path.dirname(copy_path), exist_ok=True)
            with open(copy_path, "w", encoding="utf-8") as f:
                f.write(polished_copy)
    except Exception as e:
        print(f"ContentCreationGraph: Error saving copy to {copy_path}: {e}")

    final_package = {
        "project_dir": state.get("project_dir", ""),
        "topic": topic,
        "output_dir": state.get("output_dir", ""),
        "image_path": image_path,
        "video_plot_path": video_plot_path,
        "video_path": video_path,
        "copy_path": copy_path,
        "extracted_frames": extracted_frames,
        "copy_text": polished_copy
    }

    return {
        "copy_text": polished_copy,
        "final_package": final_package,
        "copy_path": copy_path
    }

# ==========================================
# 🎉 HITL GATE 2: hitl_final_package_approval
# ==========================================
async def hitl_final_package_approval_node(state: ContentCreationState):
    """🎉 HITL GATE 2: Presents complete final package to user for 1-click final approval."""
    topic = state.get("topic", "")
    video_path = state.get("video_path", "")
    image_path = state.get("image_path", "")
    video_plot_path = state.get("video_plot_path", "")
    copy_path = state.get("copy_path", "")
    copy_text = state.get("copy_text", "")

    final_package = state.get("final_package") or {}

    response_text = (
        f"🎉 **[HITL GATE 2: Final Package Review & Approval]**\n\n"
        f"**Topic**: `{topic}`\n\n"
        f"### 📦 Deliverables Package\n"
        f"- **Base Image**: `{image_path}`\n"
        f"- **Video Plot Doc**: `{video_plot_path}`\n"
        f"- **Master Visual Plate**: `{video_path}`\n"
        f"- **Publication Copy File**: `{copy_path}`\n\n"
        f"### 📱 Publication Copy Preview\n"
        f"```markdown\n{copy_text}\n```\n\n"
        f"1-Click Final Approval Complete!"
    )

    return {
        "final_package": final_package,
        "messages": [AIMessage(content=response_text)]
    }

def create_graph(checkpointer=None, **kwargs):
    """Compiles and returns the generic instruction-driven content-creation graph with 2 HITL approval gates."""
    workflow = StateGraph(ContentCreationState)

    # 1. Add nodes
    workflow.add_node("setup_and_generate_image", setup_and_generate_image_node)
    workflow.add_node("draft_video_plot", draft_video_plot_node)
    workflow.add_node("audit_video_plot", audit_video_plot_node)
    workflow.add_node("hitl_image_and_plot_approval", hitl_image_and_plot_approval_node)
    workflow.add_node("generate_visual_plate", generate_visual_plate_node)
    workflow.add_node("extract_and_qc_frames", extract_and_qc_frames_node)
    workflow.add_node("draft_and_save_copy", draft_and_save_copy_node)
    workflow.add_node("hitl_final_package_approval", hitl_final_package_approval_node)

    # 2. Add edges
    workflow.add_edge(START, "setup_and_generate_image")
    workflow.add_edge("setup_and_generate_image", "draft_video_plot")
    workflow.add_edge("draft_video_plot", "audit_video_plot")

    workflow.add_conditional_edges(
        "audit_video_plot",
        should_continue_video_plot_audit,
        {
            "draft_video_plot": "draft_video_plot",
            "hitl_image_and_plot_approval": "hitl_image_and_plot_approval"
        }
    )

    workflow.add_edge("hitl_image_and_plot_approval", "generate_visual_plate")
    workflow.add_edge("generate_visual_plate", "extract_and_qc_frames")

    workflow.add_conditional_edges(
        "extract_and_qc_frames",
        should_continue_video_qc,
        {
            "generate_visual_plate": "generate_visual_plate",
            "draft_and_save_copy": "draft_and_save_copy"
        }
    )

    workflow.add_edge("draft_and_save_copy", "hitl_final_package_approval")
    workflow.add_edge("hitl_final_package_approval", END)

    # Compile with interrupt_before at both HITL approval gates
    return workflow.compile(
        checkpointer=checkpointer,
        interrupt_before=["hitl_image_and_plot_approval", "hitl_final_package_approval"]
    )

# Default compiled instance
graph = create_graph()

def prepare_input(query: str, caller: Optional[str] = None, **kwargs) -> Dict[str, Any]:
    """Translates incoming text query / kwargs into initial generic ContentCreationState."""
    if caller and "<caller>" not in query:
        formatted_query = f"<caller>{caller}</caller>\n{query}"
    else:
        formatted_query = query

    project_dir = kwargs.get("project_dir")
    if not project_dir:
        m_pdir = re.search(r'project_dir[:=]\s*["\']?([^"\'\s,]+)["\']?', query, re.IGNORECASE)
        if m_pdir:
            project_dir = m_pdir.group(1)
        else:
            project_dir = "pkm/wiki/software/ayla-first-words"

    topic = kwargs.get("topic") or kwargs.get("word")
    if not topic:
        m_topic = re.search(r'(?:topic|word)[:=]\s*["\']?([a-zA-Z0-9_ -]+)["\']?', query, re.IGNORECASE)
        if m_topic:
            topic = m_topic.group(1).strip()
        else:
            clean_q = query.replace("<caller>", "").replace("</caller>", "").strip()
            if clean_q and len(clean_q.split()) == 1:
                topic = clean_q
            elif "dog" in clean_q.lower():
                topic = "dog"
            elif "cat" in clean_q.lower():
                topic = "cat"
            else:
                topic = clean_q if clean_q else "scene"

    manifest_path = kwargs.get("manifest_path") or f"{project_dir}/01_Project_Manifest.md"
    creator_instructions_path = kwargs.get("creator_instructions_path") or f"{project_dir}/02_Creator_Instructions.md"
    qc_playbook_path = kwargs.get("qc_playbook_path") or f"{project_dir}/03_QC_Playbook.md"

    output_dir = kwargs.get("output_dir") or f"{project_dir}/assets/{topic}"
    image_path = kwargs.get("image_path") or f"{output_dir}/{topic}_image.jpg"
    video_plot_path = kwargs.get("video_plot_path") or f"{output_dir}/{topic}_video_plot.md"
    video_path = kwargs.get("video_path") or f"{output_dir}/{topic}_video.mp4"
    copy_path = kwargs.get("copy_path") or f"{output_dir}/{topic}_copy.md"
    qc_timestamps = kwargs.get("qc_timestamps") or [1.0, 2.5, 4.0]

    session_id = kwargs.get("session_id", f"session_{topic}")

    return {
        "project_dir": project_dir,
        "topic": topic,
        "manifest_path": manifest_path,
        "creator_instructions_path": creator_instructions_path,
        "qc_playbook_path": qc_playbook_path,
        "output_dir": output_dir,
        "image_path": image_path,
        "video_plot_path": video_plot_path,
        "video_path": video_path,
        "copy_path": copy_path,
        "image_prompt": "",
        "video_plot_content": "",
        "video_plot_qc_passed": False,
        "video_plot_feedback": "",
        "extracted_frames": [],
        "qc_timestamps": qc_timestamps,
        "video_qc_passed": False,
        "video_qc_feedback": "",
        "copy_text": "",
        "final_package": {},
        "video_plot_attempts": 0,
        "messages": [HumanMessage(content=formatted_query)],
        "query": formatted_query,
        "session_id": session_id,
        "error_message": ""
    }

def format_output(state: Dict[str, Any]) -> str:
    """Extracts final reply text from ContentCreationState."""
    if isinstance(state, dict):
        if "messages" in state and state["messages"]:
            last_msg = state["messages"][-1]
            if isinstance(last_msg, AIMessage):
                return last_msg.content
            elif isinstance(last_msg, dict) and last_msg.get("role") == "assistant":
                return last_msg.get("content", "")
        if state.get("final_package") and "copy_text" in state["final_package"]:
            return state["final_package"]["copy_text"]
        if state.get("copy_text"):
            return state["copy_text"]
        if state.get("video_plot_qc_passed") and state.get("image_path"):
            topic = state.get("topic", "scene")
            image_path = state.get("image_path", "")
            video_plot_path = state.get("video_plot_path", "")
            return (
                f"🛑 **[HITL GATE 1: Image & Video Plot Approval Required]**\n\n"
                f"- **Topic**: `{topic}`\n"
                f"- **Base Image**: `{image_path}`\n"
                f"- **Video Plot Doc**: `{video_plot_path}`\n\n"
                f"Base image and video plot have passed QC and are ready for approval before generating video."
            )
        if state.get("error_message"):
            return f"Content creation failed: {state['error_message']}"
        if "messages" in state and state["messages"]:
            last_msg = state["messages"][-1]
            if hasattr(last_msg, "content"):
                return last_msg.content
            elif isinstance(last_msg, dict) and "content" in last_msg:
                return last_msg["content"]
            return str(last_msg)
    return str(state)
