import os
import re
import operator
from datetime import datetime, timezone
from typing import TypedDict, List, Dict, Any, Annotated, Sequence, Optional, Literal
from langchain_core.messages import BaseMessage

class ContentCreationState(TypedDict, total=False):
    # --- Project Context & Threading ---
    project_dir: str                  # e.g., "pkm/wiki/software/ayla-first-words"
    topic: str                        # e.g., "fish"
    session_id: str                   # e.g., "session_1"
    thread_id: str                    # Standard thread identifier

    # --- Instruction Documents ---
    manifest_path: str                # e.g., "{project_dir}/01_Project_Manifest.md"
    creator_instructions_path: str    # e.g., "{project_dir}/02_Creator_Instructions.md"
    qc_playbook_path: str             # e.g., "{project_dir}/03_QC_Playbook.md"
    execution_log_path: str           # e.g., "{output_dir}/execution_log.md"

    # --- Asset Paths & Versioning ---
    output_dir: str                   # e.g., "{project_dir}/words/{topic}"
    image_version: int                # e.g., 1, 2, 3
    video_plot_version: int           # e.g., 1, 2, 3
    video_version: int                # e.g., 1, 2, 3
    copy_version: int                 # e.g., 1, 2, 3

    image_path: str                   # e.g., "{output_dir}/{topic}_image_v{image_version}.jpg"
    video_plot_path: str              # e.g., "{output_dir}/{topic}_video_plot_v{video_plot_version}.md"
    video_path: str                   # e.g., "{output_dir}/{topic}_video_v{video_version}.mp4"
    copy_path: str                    # e.g., "{output_dir}/{topic}_copy_v{copy_version}.md"

    # --- Internal Graph State & QC ---
    image_prompt: str
    video_plot_content: str
    video_plot_qc_passed: bool
    video_plot_feedback: str
    qc_rejection_target: Literal["image", "plot", "both"]

    extracted_frames: List[str]       # Generated by extract_video_frames
    qc_timestamps: List[float]        # Configurable list of timestamps, default [1.0, 2.5, 4.0]
    video_qc_passed: bool
    video_qc_feedback: str

    copy_text: str
    final_package: Dict[str, Any]

    # --- HITL Multi-Turn Feedback State ---
    gate1_decision: Literal["approved", "revise_image", "revise_plot", "clarify"]
    gate2_decision: Literal["approved", "revise_copy", "revise_video", "clarify"]
    latest_human_feedback: str
    revision_history: List[Dict[str, Any]]
    clarification_question: str

    # --- Auxiliary / Runtime State ---
    video_plot_attempts: int
    max_video_plot_reviews: int
    video_qc_attempts: int
    max_video_reviews: int
    messages: Annotated[Sequence[BaseMessage], operator.add]
    query: str
    error_message: str


def normalize_project_path(path: Optional[str]) -> str:
    """Normalizes path by stripping extra slashes or relative components while keeping clean format."""
    if not path:
        return ""
    return os.path.normpath(str(path))


def _resolve_asset_path(base_or_default_path: Optional[str], output_dir: Optional[str], topic: str, asset_type: str, version: int) -> str:
    """Resolves deterministic versioned asset path."""
    topic = str(topic).strip().lower()
    out_dir = str(output_dir) if output_dir is not None else ""
    ext_map = {
        "image": "jpg",
        "video_plot": "md",
        "video": "mp4",
        "copy": "md"
    }
    ext = ext_map.get(asset_type, "dat")
    v_str = f"_v{version}" if version > 1 else ""

    if base_or_default_path and not base_or_default_path.endswith(f"_{asset_type}.{ext}"):
        dir_name = os.path.dirname(base_or_default_path)
        base_name, fext = os.path.splitext(os.path.basename(base_or_default_path))
        clean_name = re.sub(r'_v\d+$', '', base_name)
        return os.path.join(dir_name or out_dir, f"{clean_name}{v_str}{fext or f'.{ext}'}")
    return os.path.join(out_dir, f"{topic}_{asset_type}{v_str}.{ext}")


def _append_execution_log(
    output_dir: Optional[str],
    topic: str,
    actor: str,
    event_title: str,
    details: Dict[str, Any],
    log_path: Optional[str] = None
):
    """Continuously appends timestamped markdown audit log entries to execution_log.md."""
    try:
        topic_clean = str(topic or "scene").strip().lower()
        out_dir = str(output_dir) if output_dir is not None else ""
        target_file = log_path or (os.path.join(out_dir, "execution_log.md") if out_dir else "execution_log.md")
        target_dir = os.path.dirname(target_file)
        if target_dir:
            os.makedirs(target_dir, exist_ok=True)
        is_new = not os.path.exists(target_file)
        now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        time_short = datetime.now(timezone.utc).strftime("%H:%M:%S")

        with open(target_file, "a", encoding="utf-8") as f:
            if is_new:
                f.write(f"# 📜 Content Creation Trajectory: {topic_clean}\n\n")
                f.write(f"- **Topic**: `{topic_clean}`\n")
                f.write(f"- **Output Directory**: `{output_dir}`\n")
                f.write(f"- **Initiated At**: `{now_str}`\n\n")
                f.write("---\n\n")

            f.write(f"## {actor} [{time_short}] — {event_title}\n")
            for k, v in details.items():
                if v is None or v == "":
                    continue
                if isinstance(v, str) and ("\n" in v or len(v) > 80):
                    f.write(f"- **{k}**:\n```markdown\n{v.strip()}\n```\n")
                elif isinstance(v, list):
                    f.write(f"- **{k}**:\n")
                    for item in v:
                        f.write(f"  - `{item}`\n")
                else:
                    f.write(f"- **{k}**: `{v}`\n")
            f.write("\n")
    except Exception as e:
        print(f"ContentCreationGraph: Error appending to execution_log.md: {e}")


def _extract_motion_prompt_from_plot(plot_content: str, state: Dict[str, Any]) -> str:
    """Extracts the motion prompt blockquote under **Prompt:** or Motion Prompt header from the Video Plot Markdown."""
    topic = state.get("topic", "scene")
    if plot_content:
        lines = plot_content.split("\n")
        in_prompt = False
        prompt_lines = []
        for line in lines:
            if "Motion Prompt" in line or "**Prompt:**" in line:
                in_prompt = True
                if "**Prompt:**" in line:
                    parts = line.split("**Prompt:**", 1)
                    if len(parts) > 1 and parts[1].strip():
                        prompt_lines.append(parts[1].strip().lstrip(">").strip())
                continue
            if in_prompt:
                if line.startswith("---") or line.startswith("## ") or line.startswith("# "):
                    break
                if line.strip().startswith(">"):
                    prompt_lines.append(line.strip().lstrip(">").strip())
                elif prompt_lines and not line.strip():
                    break
                elif prompt_lines:
                    prompt_lines.append(line.strip())
        if prompt_lines:
            extracted = " ".join(prompt_lines).strip()
            if extracted:
                return extracted

    return f"Cinematic video scene for topic: {topic}. High quality, smooth camera movement, focused subject animation."
