import os
import re
import operator
from datetime import datetime, timezone
from typing import TypedDict, List, Dict, Any, Annotated, Sequence, Optional, Literal
from langchain_core.messages import BaseMessage

class ContentCreationState(TypedDict, total=False):
    # --- Project Context & Threading ---
    project_dir: str                  # e.g., "pkm/wiki/software/ayla-first-words"
    topic: str                        # e.g., "fish"
    session_id: str                   # e.g., "session_1"
    thread_id: str                    # Standard thread identifier

    # --- Instruction Documents ---
    manifest_path: str                # e.g., "{project_dir}/01_Project_Manifest.md"
    creator_instructions_path: str    # e.g., "{project_dir}/02_Creator_Instructions.md"
    qc_playbook_path: str             # e.g., "{project_dir}/03_QC_Playbook.md"
    execution_log_path: str           # e.g., "{output_dir}/execution_log.md"

    # --- Asset Paths & Versioning ---
    output_dir: str                   # e.g., "{project_dir}/words/{topic}"
    image_version: int                # e.g., 1, 2, 3
    video_plot_version: int           # e.g., 1, 2, 3
    video_version: int                # e.g., 1, 2, 3
    copy_version: int                 # e.g., 1, 2, 3

    image_path: str                   # e.g., "{output_dir}/{topic}_image_v{image_version}.jpg"
    video_plot_path: str              # e.g., "{output_dir}/{topic}_video_plot_v{video_plot_version}.md"
    raw_video_path: str               # e.g., "{output_dir}/{topic}_visual_plate_v{video_version}.mp4"
    video_path: str                   # e.g., "{output_dir}/{topic}_video_v{video_version}.mp4" (remixed master)
    copy_path: str                    # e.g., "{output_dir}/{topic}_copy_v{copy_version}.md"
    audio_path: str                   # e.g., "{output_dir}/{topic}_wav.wav"
    overlay_text: str                 # e.g., "魚" or topic name

    # --- Internal Graph State & QC ---
    image_prompt: str
    video_plot_content: str
    video_plot_qc_passed: bool
    video_plot_feedback: str
    qc_rejection_target: Literal["image", "plot", "both"]

    remix_actions: List[Dict[str, Any]]
    audio_verified: bool
    extracted_frames: List[str]       # Generated by extract_video_frames
    qc_timestamps: List[float]        # Configurable list of timestamps, default [1.0, 2.5, 4.0]
    video_qc_passed: bool
    video_qc_feedback: str
    video_qc_rejection_target: Literal["visual_plate", "remix", "both"]
    video_persisted: bool
    video_generation_error: str

    copy_text: str
    final_package: Dict[str, Any]

    # --- HITL Multi-Turn Feedback State ---
    gate1_decision: Literal["approved", "revise_image", "revise_plot", "clarify"]
    gate2_decision: Literal["approved", "revise_copy", "revise_video", "clarify"]
    latest_human_feedback: str
    revision_history: List[Dict[str, Any]]
    clarification_question: str

    # --- Auxiliary / Runtime State ---
    video_plot_attempts: int
    max_video_plot_reviews: int
    video_qc_attempts: int
    max_video_reviews: int
    messages: Annotated[Sequence[BaseMessage], operator.add]
    query: str
    error_message: str


def normalize_project_path(path: Optional[str]) -> str:
    """Normalizes path by stripping extra slashes or relative components while keeping clean format."""
    if not path:
        return ""
    return os.path.normpath(str(path))


def _resolve_project_doc_path(doc_path: Optional[str], project_dir: Optional[str], default_filename: str) -> str:
    """Resolves instruction document path strictly under project_dir."""
    pdir = normalize_project_path(project_dir)
    if not pdir:
        return doc_path or ""
    if doc_path:
        norm_doc = normalize_project_path(doc_path)
        if norm_doc.startswith(pdir):
            return norm_doc
        return os.path.join(pdir, os.path.basename(doc_path))
    return os.path.join(pdir, default_filename)


def _resolve_asset_path(base_or_default_path: Optional[str], output_dir: Optional[str], topic: str, asset_type: str, version: int) -> str:
    """Resolves deterministic versioned asset path strictly under output_dir."""
    topic = str(topic).strip().lower()
    out_dir = normalize_project_path(output_dir)
    ext_map = {
        "image": "jpg",
        "video_plot": "md",
        "raw_video": "mp4",
        "visual_plate": "mp4",
        "video": "mp4",
        "copy": "md",
        "audio": "wav"
    }
    ext = ext_map.get(asset_type, "dat")
    v_str = f"_v{version}" if version > 1 else ""

    if base_or_default_path:
        norm_path = normalize_project_path(base_or_default_path)
        dir_name = os.path.dirname(norm_path)
        base_name, fext = os.path.splitext(os.path.basename(norm_path))
        clean_name = re.sub(r'_v\d+$', '', base_name)
        if out_dir and norm_path.startswith(out_dir):
            return os.path.join(dir_name, f"{clean_name}{v_str}{fext or f'.{ext}'}")
        resolved_dir = out_dir or dir_name
        if resolved_dir:
            return os.path.join(resolved_dir, f"{clean_name}{v_str}{fext or f'.{ext}'}")
        return f"{clean_name}{v_str}{fext or f'.{ext}'}"

    if out_dir:
        return os.path.join(out_dir, f"{topic}_{asset_type}{v_str}.{ext}")
    return f"{topic}_{asset_type}{v_str}.{ext}"


def _append_execution_log(
    output_dir: Optional[str],
    topic: str,
    actor: str,
    event_title: str,
    details: Dict[str, Any],
    log_path: Optional[str] = None
):
    """Continuously appends timestamped markdown audit log entries to execution_log.md."""
    try:
        topic_clean = str(topic or "scene").strip().lower()
        out_dir = str(output_dir) if output_dir is not None else ""
        target_file = log_path or (os.path.join(out_dir, "execution_log.md") if out_dir else "")
        if not target_file:
            return
        target_dir = os.path.dirname(target_file)
        if target_dir:
            os.makedirs(target_dir, exist_ok=True)
        is_new = not os.path.exists(target_file)
        now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        time_short = datetime.now(timezone.utc).strftime("%H:%M:%S")

        with open(target_file, "a", encoding="utf-8") as f:
            if is_new:
                f.write(f"# 📜 Content Creation Trajectory: {topic_clean}\n\n")
                f.write(f"- **Topic**: `{topic_clean}`\n")
                f.write(f"- **Output Directory**: `{output_dir}`\n")
                f.write(f"- **Initiated At**: `{now_str}`\n\n")
                f.write("---\n\n")

            f.write(f"## {actor} [{time_short}] — {event_title}\n")
            for k, v in details.items():
                if v is None or v == "":
                    continue
                if isinstance(v, str) and ("\n" in v or len(v) > 80):
                    f.write(f"- **{k}**:\n```markdown\n{v.strip()}\n```\n")
                elif isinstance(v, list):
                    f.write(f"- **{k}**:\n")
                    for item in v:
                        f.write(f"  - `{item}`\n")
                else:
                    f.write(f"- **{k}**: `{v}`\n")
            f.write("\n")
    except Exception as e:
        print(f"ContentCreationGraph: Error appending to execution_log.md: {e}")


def _extract_motion_prompt_from_plot(plot_content: str, state: Dict[str, Any]) -> str:
    """Extracts the motion prompt blockquote under **Prompt:** or Motion Prompt header from the Video Plot Markdown."""
    topic = state.get("topic", "scene")
    if plot_content:
        lines = plot_content.split("\n")
        in_prompt = False
        prompt_lines = []
        for line in lines:
            if "Motion Prompt" in line or "**Prompt:**" in line:
                in_prompt = True
                if "**Prompt:**" in line:
                    parts = line.split("**Prompt:**", 1)
                    if len(parts) > 1 and parts[1].strip():
                        prompt_lines.append(parts[1].strip().lstrip(">").strip())
                continue
            if in_prompt:
                if line.startswith("---") or line.startswith("## ") or line.startswith("# "):
                    break
                if line.strip().startswith(">"):
                    prompt_lines.append(line.strip().lstrip(">").strip())
                elif prompt_lines and not line.strip():
                    break
                elif prompt_lines:
                    prompt_lines.append(line.strip())
        if prompt_lines:
            extracted = " ".join(prompt_lines).strip()
            if extracted:
                return extracted

    return f"Cinematic video scene for topic: {topic}. High quality, smooth camera movement, focused subject animation."


def _extract_remix_actions_from_plot(plot_content: str, state: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Extracts add_audio and add_text action configurations from the Video Plot Markdown or state."""
    topic = str(state.get("topic") or "scene").strip().lower()
    output_dir = normalize_project_path(state.get("output_dir", ""))
    
    # 1. Determine Audio Path & parameters
    audio_path = state.get("audio_path")
    if not audio_path and output_dir:
        # Check standard candidates
        for candidate_ext in [f"{topic}_wav.wav", f"{topic}.wav", f"{topic}.m4a", f"{topic}.mp3"]:
            c_path = os.path.join(output_dir, candidate_ext)
            if os.path.isfile(c_path):
                audio_path = c_path
                break
        if not audio_path:
            audio_path = os.path.join(output_dir, f"{topic}_wav.wav")

    # Search for custom audio path in plot markdown
    audio_start_time = 1.5
    audio_vol = 1.8
    if plot_content:
        m_audio = re.search(r'(?:Source Audio|Audio Path)[:=]\s*`?([^`\n\r]+)`?', plot_content, re.IGNORECASE)
        if m_audio:
            parsed_audio = m_audio.group(1).strip()
            if parsed_audio:
                audio_path = parsed_audio
        m_astart = re.search(r'(?:Audio Start Time|Audio Timing)[:=]\s*`?([0-9.]+s?)`?', plot_content, re.IGNORECASE)
        if m_astart:
            audio_start_time = m_astart.group(1).strip()
        m_avol = re.search(r'(?:Audio Volume|Volume)[:=]\s*`?([0-9.]+)`?', plot_content, re.IGNORECASE)
        if m_avol:
            try:
                audio_vol = float(m_avol.group(1).strip())
            except Exception:
                pass

    actions: List[Dict[str, Any]] = []

    if audio_path:
        actions.append({
            "action": "add_audio",
            "audio_path": audio_path,
            "start_time": audio_start_time,
            "volume": audio_vol,
            "original_volume": 0.6,
            "blend_mode": "blend"
        })

    # 2. Determine Text Overlay parameters
    text_content = state.get("overlay_text")
    text_start_time = 1.5
    text_end_time = 3.5
    font_size = 110
    font_color = "white"
    border_color = "0x4A3B32"
    border_width = 8

    if plot_content:
        m_text = re.search(r'(?:Text Overlay|Overlay Text|Text Content|Display Text|Word Text)[:=]\s*["`]?([^"`\n\r]+)["`]?', plot_content, re.IGNORECASE)
        if m_text:
            text_content = m_text.group(1).strip()
        m_tstart = re.search(r'(?:Text Start Time|Text Start)[:=]\s*`?([0-9.]+s?)`?', plot_content, re.IGNORECASE)
        if m_tstart:
            text_start_time = m_tstart.group(1).strip()
        m_tend = re.search(r'(?:Text End Time|Text End)[:=]\s*`?([0-9.]+s?)`?', plot_content, re.IGNORECASE)
        if m_tend:
            text_end_time = m_tend.group(1).strip()

    if not text_content:
        text_content = topic

    actions.append({
        "action": "add_text",
        "text": text_content,
        "start_time": text_start_time,
        "end_time": text_end_time,
        "font_size": font_size,
        "font_color": font_color,
        "border_color": border_color,
        "border_width": border_width,
        "x": "(w-text_w)/2",
        "y": "h*0.22"
    })

    return actions

